[package]
name = "mago-token"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
mago-span = { path = "../span" }
mago-interner = { path = "../interner" }
serde = { workspace = true }
strum = { workspace = true }
