[package]
name = "fennec-typing"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ahash = { workspace = true }
fennec-reflection = { path = "../reflection" }
fennec-span = { path = "../span" }
fennec-semantics = { path = "../semantics" }
fennec-names = { path = "../names" }
fennec-interner = { path = "../interner" }
fennec-trinary = { path = "../trinary" }
fennec-ast = { path = "../ast" }
ordered-float = { workspace = true }
