[package]
name = "mago-typing"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
mago-ast = { workspace = true }
mago-reflection = { workspace = true }
mago-span = { workspace = true }
mago-semantics = { workspace = true }
mago-names = { workspace = true }
mago-interner = { workspace = true }
mago-trinary = { workspace = true }
ahash = { workspace = true }
ordered-float = { workspace = true }
