[package]
name = "mago-typing"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ahash = { workspace = true }
mago-reflection = { path = "../reflection" }
mago-span = { path = "../span" }
mago-semantics = { path = "../semantics" }
mago-names = { path = "../names" }
mago-interner = { path = "../interner" }
mago-trinary = { path = "../trinary" }
mago-ast = { path = "../ast" }
ordered-float = { workspace = true }
