[package]
name = "mago-span"
edition.workspace = true
authors.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
mago-source = { path = "../source" }
serde = { workspace = true }
