[package]
name = "mago-trinary"
description = "A library implementing three-valued logical operations (true, false, maybe) to handle complex logical reasoning scenarios."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
strum = { workspace = true }
