[package]
name = "mago-wasm"
description = "Exposes PHP code analysis and tooling functionalities as WebAssembly modules, enabling browser-based tools and editor integrations."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
mago-ast = { workspace = true }
mago-names = { workspace = true }
mago-interner = { workspace = true }
mago-reporting = { workspace = true }
mago-semantics = { workspace = true }
mago-symbol-table = { workspace = true }
mago-source = { workspace = true }
mago-parser = { workspace = true }
mago-formatter = { workspace = true }
wasm-bindgen = { workspace = true }
serde-wasm-bindgen = { workspace = true }
getrandom = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
