[package]
name = "mago-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { workspace = true }
serde-wasm-bindgen = { workspace = true }
getrandom = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
mago-ast = { path = "../ast" }
mago-names = { path = "../names" }
mago-interner = { path = "../interner" }
mago-reporting = { path = "../reporting" }
mago-semantics = { path = "../semantics" }
mago-symbol-table = { path = "../symbol-table" }
mago-source = { path = "../source" }
mago-parser = { path = "../parser" }
mago-formatter = { path = "../formatter" }
